#!/bin/bash

set -e

print_help() {
  printf "%s\n%s\n" "Usage:" \
                    "  ostree-compliance-mode-helper enable"
  exit 0
}

confirm_continuation() {
  while true; do
    read -p "Are you sure you want to proceed? (yes/no) " yn

    case $yn in
      yes ) break;;
      no ) printf "exiting...\n";
           exit;;
      * ) printf "invalid response\n";;
    esac
  done
}

if [ "$1" != "enable" ]; then
  print_help
fi

if [ $EUID != 0 ]; then
  echo "This script must be run as root"
  exit 1
fi

if ! command -v ostree > /dev/null; then
  printf "ostree-compliance-mode assumes ostree is installed\n"
  exit 2
fi

if ! command -v rpm-ostree > /dev/null; then
  printf "ostree-compliance-mode assumes rpm-ostree is installed\n"
  exit 3
fi

if [ $(rpm-ostree status --json | grep -i -m1 "\"booted\""  | awk '{printf $3}') != "true," ]; then
  printf "First deployment in 'rpm-ostree status --json', should always be true\n"
  exit 4
fi

currently_deployed_ref=$(rpm-ostree status --json | grep -i -m1 "\"origin\"" | awk -F'"' '{print $4}')
devmode_ref=$(head -n1 /etc/ostree-compliance-mode.conf)

if [ "$currently_deployed_ref" != "$devmode_ref" ]; then # 1st iteration
  printf "Enabling ostree-compliance-mode will leave the vehicle in an undrivable state removing proprietary data, this will also force a reboot\n"
  confirm_continuation
  ostree admin deploy $devmode_ref
  reboot
else # 2nd iteration
  printf "Enabling ostree-compliance-mode will leave the vehicle in an undrivable state removing proprietary data\n"
  confirm_continuation
  # delete all refs except for the compliance-mode one and special ostree ones
  for i in $(ostree refs); do
    if [ "$i" != "^ostree" ] && [ "$i" != "$devmode_ref" ]; then
      ostree refs --delete $i
    fi
  done

  rpm-ostree cleanup -pr # cleanup everything except booted deployment
  ostree prune --refs-only # now finally prune the other refs
  exec /bin/bash # grant root access at this point
fi

